import { Crimson_Pro } from "next/font/google";
import "./globals.css";
// import Link from "next/link";
import NavBar from './component/navbar.js';
// import { Component } from "react";

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

export const metadata = {
  title: "UConn LPhiE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${crimsonPro.variable}`}>
        <NavBar   />
        {children}
        <div className="tmpFooter"></div>
      </body>
    </html>
  );
}
